---
abstract: 'JWT utilities.'
author:
  - 'NAGAYA Shinichiro <clairvy@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.87_01
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-JWT
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Crypt::OpenSSL::RSA: 0.28
  Digest::SHA: 5.63
  JSON: 2.53
  MIME::Base64: 3.13
  Try::Tiny: 0.09
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/clairvy/p5-Acme-JWT.git
version: 0.03
